name: ArmorHider
main: s0b.armhidplugin.ArmorHiderPlugin
version: 1.0
api-version: 1.20
depend: [ProtocolLib]
commands:
  esconder:
    description: Esconde a armadura
  mostrar:
    description: Mostra a armadura